#include "buynshare_generated.h"
#include "fridge_generated.h"
#include "fridges_generated.h"
#include "fridgepurchases_generated.h"
#include "fridgeusers_generated.h"
#include "meal_generated.h"
#include "userfridges_generated.h"
#include "userpurchases_generated.h"
#include "fridgemealcards_generated.h"
#include "fridgeuser_generated.h"
#include "mealcard_generated.h"
#include "purchase_generated.h"
#include "user_generated.h"

#define MSG_INTERRUPTED 			"Interrupted "
#define MSG_RELOAD_CONFIG_REQUEST	"Re-read config request "
