<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace bs;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class Meal extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return Meal
     */
    public static function getRootAsMeal(ByteBuffer $bb)
    {
        $obj = new Meal();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return Meal
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    public function getCn()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    public function getLocale()
    {
        $o = $this->__offset(6);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startMeal(FlatBufferBuilder $builder)
    {
        $builder->StartObject(2);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return Meal
     */
    public static function createMeal(FlatBufferBuilder $builder, $cn, $locale)
    {
        $builder->startObject(2);
        self::addCn($builder, $cn);
        self::addLocale($builder, $locale);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addCn(FlatBufferBuilder $builder, $cn)
    {
        $builder->addOffsetX(0, $cn, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addLocale(FlatBufferBuilder $builder, $locale)
    {
        $builder->addOffsetX(1, $locale, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endMeal(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
