GRANT ALL ON TABLE fridge TO commandu_buynshare1;
GRANT ALL ON TABLE fridgeuser TO commandu_buynshare1;
GRANT ALL ON TABLE meal TO commandu_buynshare1;
GRANT ALL ON TABLE mealcard TO commandu_buynshare1;
GRANT ALL ON TABLE purchase TO commandu_buynshare1;
GRANT ALL ON TABLE "user" TO commandu_buynshare1;
GRANT ALL ON TABLE vote TO commandu_buynshare1;

DELETE FROM "fridgeuser";
SELECT setval('fridgeuser_id_seq', 1, true);
DELETE FROM "vote";
SELECT setval('vote_id_seq', 1, true);
DELETE FROM "purchase";
SELECT setval('purchase_id_seq', 1, true);
DELETE FROM "mealcard";
SELECT setval('mealcard_id_seq', 1, true);
DELETE FROM "fridge";
SELECT setval('fridge_id_seq', 1, true);
DELETE FROM "meal";
SELECT setval('meal_id_seq', 1, true);
DELETE FROM "user";
SELECT setval('user_id_seq', 1, true);
