DELETE FROM "fridgeuser";
SELECT setval('fridgeuser_id_seq', 1, true);
DELETE FROM "fridge";
SELECT setval('fridge_id_seq', 1, true);
DELETE FROM "meal";
SELECT setval('meal_id_seq', 1, true);
DELETE FROM "mealcard";
SELECT setval('mealcard_id_seq', 1, true);
DELETE FROM "purchase";
SELECT setval('purchase_id_seq', 1, true);
DELETE FROM "vote";
SELECT setval('vote_id_seq', 1, true);
DELETE FROM "user";
SELECT setval('user_id_seq', 1, true);
